ROLLBACK;
BEGIN;

DROP TABLE IF EXISTS test_list CASCADE;

CREATE TEMPORARY TABLE test_list (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  value INT NOT NULL,
  PRIMARY KEY(id, value)
)
PARTITION BY LIST (value);

CREATE TEMPORARY TABLE test_list_1 PARTITION OF test_list (value)
FOR VALUES IN (0, 1, 2);

CREATE TEMPORARY TABLE test_list_2 PARTITION OF test_list (value)
FOR VALUES IN (3, 4);

CREATE TEMPORARY TABLE test_list_rest PARTITION OF test_list (value) DEFAULT;

\d test_list
\d test_list_1
\d test_list_2
\d test_list_rest
\prompt '' _

INSERT INTO test_list (value)
  (SELECT random() FROM generate_series(0, 10000) as t(x));


CREATE TEMPORARY TABLE test_hash (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  value INT NOT NULL,
  PRIMARY KEY(id, value)
)
PARTITION BY HASH (value);

CREATE TEMPORARY TABLE test_hash_0 PARTITION OF test_hash (value)
FOR VALUES WITH (MODULUS 3, REMAINDER 0);

CREATE TEMPORARY TABLE test_hash_1 PARTITION OF test_hash (value)
FOR VALUES WITH (MODULUS 3, REMAINDER 1);

CREATE TEMPORARY TABLE test_hash_2 PARTITION OF test_hash (value)
FOR VALUES WITH (MODULUS 3, REMAINDER 2);

INSERT INTO test_hash (value)
  (SELECT random(0, 10) FROM generate_series(0, 10000) as t(x));
