DROP TABLE IF EXISTS t1, t2 CASCADE;

create temporary table t1 (
  id bigint primary key generated by default as identity,
  x int not null,
  y numeric(5,2) not null default 0
);
insert into t1 (id, x)
  (select x * 2, random(0, 100) from generate_series(1, 100) t(x));

create temporary table t2 (
  id bigint primary key generated by default as identity,
  value text
);
insert into t2 (id, value)
  (select x * 3, random(0, 100) from generate_series(1, 100) t(x));

merge into t1
  using t2 as x on t1.id = x.id
when matched and (t1.id > 20 and t1.id < 70)
  then delete
when matched
  then update set y = cast(x.value as numeric(5,2))
when not matched by target
  then insert (id, x, y) VALUES (x.id, cast(x.value as int) * x.id, 1)

when not matched by source
  then update set y = -1
  ;

insert into t1 (id, x)
  (select id, cast(value as int) as x from t2)
  -- ON CONFLICT (id) DO UPDATE SET x = EXCLUDED.x * 100
  ON CONFLICT ON CONSTRAINT t1_pkey DO UPDATE SET x = EXCLUDED.x * 100
  ;

select * from t1 order by id asc;
