name:                haskellInDepth
version:             0.1.0.0
github:              "github/ynishiza"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskellInDepthProjects#readme>

dependencies:
- base >= 4.14 && < 5
- ghc-prim >= 0.6.0
- fmt
- mtl >= 2.0 && < 2.3
- transformers >= 0.5 && < 0.6
- time >=1.8 && <1.12
- bytestring >=0.10 && <0.12
- text >=1.2 && <1.3
- text-show >=3.0 && <4
- exceptions >= 0.10 && < 0.11
- extra >=1.5 && <1.8
- filepath >= 1.4.1 && < 1.5
- directory >= 1.3 && < 1.4
- unix-compat >= 0.5 && < 0.6

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- DeriveFoldable
- DeriveFunctor
- DeriveTraversable
- DeriveGeneric
- DeriveDataTypeable
- ExplicitForAll
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- MultiParamTypeClasses
- TypeSynonymInstances
- RecordWildCards

library:
  source-dirs: ./lib

executables:
  main:
    main:               main.hs
    source-dirs:        ./src/main
    dependencies: 
    - haskellInDepth
    - text
    - random
    - criterion >= 1.5.12 && < 2
    - timeit >= 2.0 && < 3

  du:
    main: Main.hs
    source-dirs: src/du
    dependencies:
      - haskellInDepth
      - directory >= 1.3 && < 1.4
      - optparse-applicative >= 0.14 && < 0.17
      - text >=1.2 && <1.3
      - text-show >=3.0 && <4
    default-extensions: []

  isprime:
    main: Main.hs
    source-dirs: src/isprime
    dependencies:
      - haskellInDepth
      - timeit >= 2.0 && < 3
    default-extensions: []

  stockquotes:
    main:                Main.hs
    source-dirs:         src/stockquotes/
    other-modules:
      - QuoteData
      - Params
      - StatReport
      - HtmlReport
      - Charts
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellInDepth
    - vector
    - blaze-html >=0.9 && <0.10
    - optparse-applicative >=0.14 && <0.17
    - Chart >=1.8 && <1.10
    - Chart-diagrams >=1.8 && <1.10
    - Chart-cairo >=1.8 && <1.10
    - cassava >=0.5 && <0.6
    - colonnade >= 1.1 && < 1.3
    - blaze-colonnade >= 1.1 && < 1.3

  suntimes:
    source-dirs: src/suntimes
    main: Main.hs
    dependencies:
      - haskellInDepth
      - aeson >= 1.2 && < 2
      - req >= 2.0 && < 3.10
      - http-client >= 0.6 && < 0.7
      - http-types >= 0.12 && < 0.13
      - optparse-applicative >= 0.14 && < 0.17
      - monad-logger
    default-extensions:
      - OverloadedStrings

  iplookup:
    source-dirs: src/ip/lookup
    main: Main.hs
    dependencies:
      - haskellInDepth 
      - split >= 0.2 && < 0.3
      - fingertree >= 0.1 && < 0.2
    default-extensions:
      - OverloadedStrings

internal-libraries:
  du-lib:
    source-dirs: ./src/du
    exposed-modules:
      - AppTypes
      - AppWRST
      - DuUtils
      - DirTree
      - FileCount
      - DiskUsage
    dependencies:
      - haskellInDepth
      - optparse-applicative >= 0.14 && < 0.17
    default-extensions: []
    other-extensions:
      - GeneralizedNewtypeDeriving

  hid-lib:
    source-dirs: ./src/main
    exposed-modules:
      # - Utils
      - Chapter1_4
      - Chapter2_1
      - Chapter5_1_3
      - Chapter5_2_1
      - Chapter5_2_2_Parser
      - Chapter5_3_1
      - Chapter6_2
      - Chapter7_3
      - Radar
    dependencies: 
      - haskellInDepth
      - criterion
      - random

  suntimes-lib:
    source-dirs: src/suntimes
    exposed-modules:
      - Types
      - App
      - GeoCoordsReq
      - SunTimes
      - STExcept
      - ProcessRequest
    dependencies:
      - haskellInDepth
      - aeson >= 1.2 && < 2
      - req >= 2.0 && < 3.10
      - http-client >= 0.6 && < 0.7
      - http-types >= 0.12 && < 0.13
      - optparse-applicative >= 0.14 && < 0.17
      - monad-logger
    default-extensions:
      - OverloadedStrings
      - RecordWildCards

  iplookup-lib:
    source-dirs: src/ip/lookup
    exposed-modules:
      - IPTypes
      - IPParse
      - IPLookup
    dependencies:
      - haskellInDepth 
      - split >= 0.2 && < 0.3
      - fingertree >= 0.1 && < 0.2
    default-extensions:
      - OverloadedStrings

  isprime-lib:
    source-dirs: src/isprime
    exposed-modules:
      - Prime
    dependencies:
      - haskellInDepth
      - timeit >= 2.0 && < 3
    default-extensions: []

tests:
  du-test: 
    main:               Main.hs
    source-dirs:      ./test/du
    dependencies: 
    - haskellInDepth
    - du-lib

  main-test:
    main:               Main.hs
    source-dirs:      ./test/main
    dependencies: 
    - haskellInDepth
    - hid-lib
    - random
    - tasty >= 0.11 && < 1.5
    - tasty-hspec >= 1.1 && < 1.2

  suntimes-test:
    main:               Main.hs
    source-dirs:      ./test/suntimes
    dependencies: 
    - haskellInDepth
    - suntimes-lib
    - hspec >= 2.5 && <= 2.10
    - tasty >= 0.11 && < 1.5
    - tasty-hspec >= 1.1 && < 1.2
    default-extensions:
      - OverloadedStrings

  iplookup-test:
    main: Main.hs
    source-dirs: test/iplookup
    dependencies:
      - haskellInDepth
      - iplookup-lib
      - tasty >= 0.11 && < 1.5
      - tasty-hspec >= 1.1 && < 1.2
      - tasty-hedgehog >= 0.1 && <= 1.2
      - hedgehog >= 0.5 && < 1.1
      - tasty-golden >= 2.3 && < 2.4
      - filepath >= 1.4.1 && < 1.5
      - random
    ghc-options:
      - -Wno-type-defaults
    default-extensions:
      - OverloadedStrings

  isprime-test:
    main: Main.hs
    source-dirs: test/isprime
    dependencies:
      - haskellInDepth
      - isprime-lib
      - hedgehog >= 0.5 && < 1.1
      - tasty >= 0.11 && < 1.5
      - tasty-hspec >= 1.1 && < 1.2
      - tasty-hedgehog >= 0.1 && <= 1.2

benchmarks:
  isprime-benchmark:
    main: Main.hs
    source-dirs: benchmark/isprime
    dependencies:
      - haskellInDepth
      - isprime-lib
      - criterion >= 1.5.12 && < 2
