name:                haskellInDepth
version:             0.1.0.0
github:              "github/ynishiza"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskellInDepthProjects#readme>

dependencies:
- base >= 4.14 && < 5
- ghc-prim >= 0.6.0
- fmt
- mtl >= 2.0 && < 2.3
- transformers >= 0.5 && < 0.6
- time >=1.8 && <1.12
- bytestring >=0.10 && <0.12
- text >=1.2 && <1.3
- text-show >=3.0 && <4
- exceptions >= 0.10 && < 0.11
- extra >=1.5 && <1.8
- filepath >= 1.4.1 && < 1.5
- directory >= 1.3 && < 1.4
- unix-compat >= 0.5 && < 0.6
- deepseq

ghc-options:
- -rtsopts=all
- -fprof-auto
- -fprof-auto-top
- -fprof-auto-calls
- -fprof-auto-exported
- -fprof-auto-calls
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- DeriveFoldable
- DeriveFunctor
- DeriveTraversable
- DeriveGeneric
- DeriveDataTypeable
- ExplicitForAll
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- MultiParamTypeClasses
- TypeSynonymInstances
- RecordWildCards

library:
  source-dirs: ./lib

executables: 
  stockquotes:
    main:                Main.hs
    source-dirs:         src/stockquotes/
    other-modules:
      - QuoteData
      - Params
      - StatReport
      - HtmlReport
      - Charts
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellInDepth
    - vector
    - blaze-html >=0.9 && <0.10
    - optparse-applicative >=0.14 && <0.17
    - Chart >=1.8 && <1.10
    - Chart-diagrams >=1.8 && <1.10
    - Chart-cairo >=1.8 && <1.10
    - cassava >=0.5 && <0.6
    - colonnade >= 1.1 && < 1.3
    - blaze-colonnade >= 1.1 && < 1.3
