name:                haskellInDepth
version:             0.1.0.0
github:              "github/ynishiza"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskellInDepthProjects#readme>

dependencies:
- base >= 4.7 && < 5
- fmt
- text
- transformers
- mtl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- DeriveFoldable
- DeriveFunctor
- DeriveTraversable
- DeriveGeneric
- DeriveDataTypeable
- ExplicitForAll
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- TypeSynonymInstances

library:
  source-dirs: ./app

executables:
  main:
    main:               main.hs
    source-dirs:        ./app/
    # exposed-modules:
    other-modules:
    - Utils
    - Chapter1
    - Chapter2
    - Radar
    dependencies: 
    - bytestring
    - text
    - fmt

  stockquotes:
    main:                main.hs
    source-dirs:         app/stockquotes/
    other-modules:
      - QuoteData
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vector
    - bytestring >=0.10 && <0.12
    - blaze-html >=0.9 && <0.10
    - optparse-applicative >=0.14 && <0.17
    - time >=1.8 && <1.12
    # - Chart >=1.8 && <1.10
    # - Chart-diagrams >=1.8 && <1.10
    - cassava >=0.5 && <0.6
    - colonnade >= 1.1 && < 1.3
    - blaze-colonnade >= 1.1 && < 1.3

# internal-libraries:
#   hid-lib:
#     source-dirs: ./app
#     exposed-modules:
#       - Utils
#       - Chapter1
#       - Chapter2
#       - Radar
#     dependencies: []

tests:
  main-test:
    main:               main.hs
    source-dirs:      ./test/
    dependencies: 
    - fmt
    - random
    - haskellInDepth
    # - hid-lib
