name:                haskellInDepthGHC9
version:             0.1.0.0
github:              "githubuser/haskellInDepthGHC9"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskellInDepthProjects#readme>

dependencies:
- base >= 4.14 && < 5
- ghc-prim >= 0.6.0
- fmt
- mtl >= 2.0 && < 2.3
- transformers >= 0.5 && < 0.6
- time >=1.8 && <1.12
- bytestring >=0.10 && <0.12
- text >=1.2 && <1.3
- text-show >=3.0 && <4
- exceptions >= 0.10 && < 0.11
- extra >=1.5 && <1.8
- filepath >= 1.4.1 && < 1.5
- directory >= 1.3 && < 1.4
- unix-compat >= 0.5 && < 0.6
- deepseq

ghc-options:
- -XHaskell2010
- -rtsopts=all
- -fprof-auto
- -fprof-auto-top
- -fprof-auto-calls
- -fprof-auto-exported
- -fprof-auto-calls
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

# NOTE: "language" field not recognized?
# language: Haskell2010

default-extensions:
- DeriveFoldable
- DeriveFunctor
- DeriveTraversable
- DeriveGeneric
- DeriveDataTypeable
- ExplicitForAll
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- MultiParamTypeClasses
- TypeSynonymInstances
- RecordWildCards
- ImportQualifiedPost

library:
  source-dirs: ./lib

executables:
  main:
    main:               main.hs
    source-dirs:        ./src/main
    dependencies: 
    - haskellInDepthGHC9
    - random
    - aeson >= 2 && <3
    - criterion >= 1.5.12 && < 2
    - timeit >= 2.0 && < 3
    - template-haskell >=2.18 && <2.19
    ghc-options: []
    # - -ddump-to-file
    # - -ddump-file-prefix=mydump
    # - -ddump-deriv

internal-libraries:
  hid-lib:
    source-dirs: ./src/main
    exposed-modules:
      - Radar
      - Chapter5_2_2_Parser
      - Chapter12.TemplateProjection
      - Chapter12.GenericsSQL
    dependencies: 
      - haskellInDepthGHC9
      - random
      - aeson >= 2 && <3
      - criterion >= 1.5.12 && < 2
      - timeit >= 2.0 && < 3
      - template-haskell >=2.18 && <2.19


tests:
  main-test:
    main:               Main.hs
    source-dirs:      ./test/main
    dependencies: 
    - haskellInDepthGHC9
    - hid-lib
    - random
    - tasty >= 0.11 && < 1.6
    - tasty-hspec >= 1.1 && < 1.3
    - tasty-hedgehog >= 0.1 && <= 1.4
    - hspec >= 0.1 && <= 3
    - hedgehog >= 0.5 && < 1.2

benchmarks: {}
