name:                haskellInDepthGHC9
version:             0.1.0.0
github:              "githubuser/haskellInDepthGHC9"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskellInDepthProjects#readme>

dependencies:
- base >= 4.14 && < 5
- ghc-prim >= 0.6.0
- fmt
- mtl >= 2.0 && < 2.3
- monad-logger >= 0.3.37 && < 0.4
- transformers >= 0.5 && < 0.6
- time >=1.8 && <1.12
- bytestring >=0.10 && <0.12
- text >=1.2 && <1.3
- text-show >=3.0 && <4
- exceptions >= 0.10 && < 0.11
- extra >=1.5 && <1.8
- filepath >= 1.4.1 && < 1.5
- directory >= 1.3 && < 1.4
- unix-compat >= 0.5 && < 0.6
- deepseq

ghc-options:
- -rtsopts=all
- -fprof-auto
- -fprof-auto-top
- -fprof-auto-calls
- -fprof-auto-exported
- -fprof-auto-calls
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints


# NOTE: "language" field not recognized?
# default-language: Haskell2010
# language: Haskell2010

default-extensions:
- Haskell2010
- DeriveFoldable
- DeriveFunctor
- DeriveTraversable
- DeriveGeneric
- DeriveDataTypeable
- ExplicitForAll
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- MultiParamTypeClasses
- TypeSynonymInstances
- RecordWildCards
- ImportQualifiedPost

library:
  source-dirs: ./lib

executables:
  main:
    main:               main.hs
    source-dirs:        ./src/main
    dependencies: 
    - haskellInDepthGHC9
    - random
    - aeson >= 2 && <3
    - criterion >= 1.5.12 && < 2
    - timeit >= 2.0 && < 3
    - template-haskell >=2.18 && <2.19
    - singletons > 3 && < 4
    - singletons-th > 3 && < 4
    - singletons-base >= 3 && < 4
    - fin > 0.2 && < 0.3
    - dec > 0.0.4 && < 1
    - streaming > 0.2 && <0.3
    - free > 5.1 && < 6
    - optparse-applicative >= 0.17 && < 0.20
    ghc-options: []
    # - -ddump-to-file
    # - -ddump-file-prefix=mydump
    # - -ddump-deriv
  radarSafe:
    main:               main.hs
    source-dirs:        ./src/radarSafe
    dependencies: 
    - haskellInDepthGHC9
    - aeson >= 2 && <3
    - template-haskell >=2.18 && <2.19
    - singletons > 3 && < 4
    - singletons-th > 3 && < 4
    - singletons-base >= 3 && < 4
    - fin > 0.2 && < 0.3
    - dec > 0.0.4 && < 1
    ghc-options:
    - -Werror=incomplete-patterns

  scratch:
    main:               main.hs
    source-dirs:        ./src/scratch
    dependencies: 
    - haskellInDepthGHC9
    - random
    - aeson >= 2 && <3
    - criterion >= 1.5.12 && < 2
    - timeit >= 2.0 && < 3
    - template-haskell >=2.18 && <2.19
    - singletons > 3 && < 4
    - singletons-th > 3 && < 4
    - singletons-base >= 3 && < 4
    - fin > 0.2 && < 0.3
    - dec > 0.0.4 && < 1
    - tasty >= 0.11 && < 1.6
    - tasty-hspec >= 1.1 && < 1.3
    - hspec >= 0.1 && <= 3

  rpc-lib:
    main:               main.hs
    source-dirs:        ./src/rpc
    dependencies:
    - cereal >= 0.5 && <0.6
    - network >= 2.8 && <3.2
    - connection >= 0.3 && <0.4
    - network-simple >=0.4.5 && <0.5
    - template-haskell >=2.18 && <2.19
    - haskell-src-exts >= 1.20 && <1.24
    - haskell-src-meta >= 0.6 && < 0.9
    - optparse-applicative >= 0.17 && < 0.20
    ghc-options: 
    - -ddump-splices

  rpc-sample:
    main:               main.hs
    source-dirs:        ./src/rpc-sample
    dependencies:
    - cereal >= 0.5 && <0.6
    - network >= 2.8 && <3.2
    - connection >= 0.3 && <0.4
    - network-simple >=0.4.5 && <0.5
    - template-haskell >=2.18 && <2.19
    - haskell-src-exts >= 1.20 && <1.24
    - haskell-src-meta >= 0.6 && < 0.9
    - optparse-applicative >= 0.17 && < 0.20

  restapi:
    main:               main.hs
    source-dirs:        ./src/restapi
    dependencies:
    - aeson >= 2 && <3
    - blaze-html > 0.9 && < 1
    - http-client > 0.7
    - servant-server > 0.19 && < 0.30
    - servant-client > 0.18 && < 0.30
    - servant-blaze > 0.9 && < 0.12
    - template-haskell >=2.18 && <2.19
    - warp > 3.3 && < 4

  dependentTypes:
    main:               main.hs
    source-dirs:        ./src/dependentTypes
    dependencies:
    - singletons > 3 && < 4
    - singletons-th > 3 && < 4
    - fin > 0.2 && < 0.3
    - some > 1 && < 2
    - dec > 0.0.4 && < 1
    - template-haskell >=2.18 && <2.19

  singletonsPart3:
    main:         main.hs
    source-dirs:  ./src/singletons/part3/
    dependencies:
    - singletons > 3 && < 4
    - singletons-th > 3 && < 4
    - singletons-base >= 3 && < 4
    ghc-options:
    - -Werror=incomplete-patterns
  singletonsPart4:
    main:         main.hs
    source-dirs:  ./src/singletons/part4/
    dependencies:
    - singletons > 3 && < 4
    - singletons-th > 3 && < 4
    - singletons-base >= 3 && < 4
    ghc-options:
    - -Werror=incomplete-patterns

  simplestream:
    main:               main.hs
    source-dirs:        ./src/simplestream
    dependencies: 
    - haskellInDepthGHC9
    - free > 5.1 && < 6
    - optparse-applicative >= 0.17 && < 0.20
    ghc-options: []

internal-libraries: {}

tests:
  main-test:
    main:               Main.hs
    source-dirs:      ./test/main
    dependencies: 
    - haskellInDepthGHC9
    - random
    - aeson >= 2 && <3
    - singletons > 3 && < 4
    - singletons-th > 3 && < 4
    - singletons-base >= 3 && < 4
    - fin > 0.2 && < 0.3
    - dec > 0.0.4 && < 1
    - streaming > 0.2 && <0.3
    - free > 5.1 && < 6
    - tasty >= 0.11 && < 1.6
    - tasty-hspec >= 1.1 && < 1.3
    - tasty-hedgehog >= 0.1 && <= 1.4
    - hspec >= 0.1 && <= 3
    - hedgehog >= 0.5 && < 1.2
    - template-haskell >=2.18 && <2.19

  rpc-test:
    main:               Main.hs
    source-dirs:      ./test/rpc
    dependencies: 
    - random
    - cereal >= 0.5 && <0.6
    - network >= 2.8 && <3.2
    - connection >= 0.3 && <0.4
    - network-simple >=0.4.5 && <0.5
    - template-haskell >=2.18 && <2.19
    - haskell-src-exts >= 1.20 && <1.24
    - haskell-src-meta >= 0.6 && < 0.9
    - optparse-applicative >= 0.17 && < 0.20
    - tasty >= 0.11 && < 1.6
    - tasty-hspec >= 1.1 && < 1.3
    - tasty-hedgehog >= 0.1 && <= 1.4
    - hspec >= 0.1 && <= 3
    - hedgehog >= 0.5 && < 1.2
    ghc-options: 
    - -ddump-splices

  restapi-test:
    main:               main.hs
    source-dirs:      ./test/restapi
    dependencies: 
    - random
    - aeson >= 2 && <3
    - http-client > 0.7 && < 0.8
    - req > 3.10 && < 3.20
    - blaze-html > 0.9 && < 1
    - http-client > 0.7
    - servant-server > 0.19 && < 0.30
    - servant-client > 0.18 && < 0.30
    - servant-blaze > 0.9 && < 0.12
    - template-haskell >=2.18 && <2.19
    - warp > 3.3 && < 4
    - tasty >= 0.11 && < 1.6
    - tasty-hspec >= 1.1 && < 1.3
    - tasty-hedgehog >= 0.1 && <= 1.4
    - hspec >= 0.1 && <= 3
    - hedgehog >= 0.5 && < 1.2
    - template-haskell >=2.18 && <2.19

  dependentTypes-test:
    main:               main.hs
    source-dirs:        ./test/dependentTypes
    dependencies:
    - singletons > 3 && < 4
    - singletons-th > 3 && < 4
    - fin > 0.2 && < 0.3
    - dec > 0.0.4 && < 1
    - some > 1 && < 2
    - template-haskell >=2.18 && <2.19
    - tasty >= 0.11 && < 1.6
    - tasty-hspec >= 1.1 && < 1.3
    - tasty-hedgehog >= 0.1 && <= 1.4
    - hspec >= 0.1 && <= 3
    - hedgehog >= 0.5 && < 1.2

  simplestream-test:
    main:               main.hs
    source-dirs:        ./test/simplestream
    dependencies: 
    - haskellInDepthGHC9
    - free > 5.1 && < 6
    - tasty >= 0.11 && < 1.6
    - tasty-hspec >= 1.1 && < 1.3
    - tasty-hedgehog >= 0.1 && <= 1.4
    - hspec >= 0.1 && <= 3
    - hedgehog >= 0.5 && < 1.2

    ghc-options: []

benchmarks: {}
