[project]
name = "airflow_playground"
version = "0.1.0"
description = ""
readme = "README.md"
# Comment
requires-python = ">=3.14"
dependencies = [
    "python-dotenv>=1.2.3",
    "structlog>=26.1.0",
]

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "apache-airflow==3.3.1",
    "python-lsp-server[all]",
    "pytest>=9.1.1",
    "ruff>=0.16.5",
    "ty>=0.0.78",
]

[tool.uv.build-backend]
module-root = "src"
module-name = "yui_airflow"

[tool.ruff]
line-length = 100
src = ["./src"]

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "SIM"]

[tool.ty.environment]
python-version = "3.14"
root = ["./airflow"]

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = ["integration: needs a Postgres DB"]
