name: Continuous Integration

on: [push]

jobs:
  TypeScript:
    runs-on: ubuntu-latest
    steps:
      - run: set
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Print version
        run: node --version

      - name: Install dependencies
        working-directory: ${{ github.workspace }}/TypeScript/
        run: make install

      - name: Run hello
        working-directory: ${{ github.workspace }}/TypeScript/
        run: make hello

      - name: Run test
        working-directory: ${{ github.workspace }}/TypeScript/
        run: make run

      - name: Cleanup
        working-directory: ${{ github.workspace }}/TypeScript/
        run: make clean

  c:
    runs-on: ubuntu-latest
    steps:
      - run: set
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile
        working-directory: ${{ github.workspace }}/c/
        run: make debug && make compile && make hacking_book_compile

      - name: Run hello
        working-directory: ${{ github.workspace }}/c/
        run: make debug && make hello

      - name: Run test
        working-directory: ${{ github.workspace }}/c/
        run: make run

      - name: Cleanup
        working-directory: ${{ github.workspace }}/c/
        run: make clean

  # Uses gh-actions-lua: https://github.com/leafo/gh-actions-lua
  lua:
    runs-on: ubuntu-latest
    steps:
      - run: set
      - name: Checkout
        uses: actions/checkout@v3
      - uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.1.5"

      - name: Run hello
        working-directory: ${{ github.workspace }}/lua/
        run: make hello

      - name: Run
        working-directory: ${{ github.workspace }}/lua/
        run: make run

  # Uses: https://github.com/haskell/actions/tree/main/setup
  haskell:
    runs-on: ubuntu-latest
    steps:
      - run: set
      - name: Checkout
        uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: '8.8' # Resolves to the latest point release of GHC 8.8
          cabal-version: '3.0.0.0' # Exact version of Cabal

      - name: Install
        working-directory: ${{ github.workspace }}/haskell/
        run: make install

      - name: Run hello
        working-directory: ${{ github.workspace }}/haskell/
        run: make hello

      - name: Run test
        working-directory: ${{ github.workspace }}/haskell/
        run: make runAll

      - name: Cleanup
        working-directory: ${{ github.workspace }}/haskell/
        run: make clean
