name: Continuous Integration

on: [push]

jobs:
  TypeScript:
    runs-on: ubuntu-latest
    steps:
      - run: set
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Print version
        run: node --version

      - name: Install dependencies
        working-directory: ${{ github.workspace }}/TypeScript/
        run: make install

      - name: Run hello
        working-directory: ${{ github.workspace }}/TypeScript/
        run: make hello

      - name: Run test
        working-directory: ${{ github.workspace }}/TypeScript/
        run: make run

      - name: Cleanup
        working-directory: ${{ github.workspace }}/TypeScript/
        run: make clean

  c:
    runs-on: ubuntu-latest
    steps:
      - run: set
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile
        working-directory: ${{ github.workspace }}/c/
        run: make debug && make compile && make hacking_book_compile

      - name: Run hello
        working-directory: ${{ github.workspace }}/c/
        run: make debug && make hello

      - name: Run test
        working-directory: ${{ github.workspace }}/c/
        run: make run

      - name: Cleanup
        working-directory: ${{ github.workspace }}/c/
        run: make clean

  # Uses gh-actions-lua: https://github.com/leafo/gh-actions-lua
  lua:
    runs-on: ubuntu-latest
    steps:
      - run: set
      - name: Checkout
        uses: actions/checkout@v3
      - uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.1.5"

      - name: Run hello
        working-directory: ${{ github.workspace }}/lua/
        run: make hello

      - name: Run
        working-directory: ${{ github.workspace }}/lua/
        run: make run

  # Uses: https://github.com/haskell/actions/tree/main/setup
  haskell:
    runs-on: ubuntu-latest
    steps:
      - run: set
      - name: Checkout
        uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.0.1' # Resolves to the latest point release of GHC 8.8
          cabal-version: '3.8' # Exact version of Cabal

      - name: Install main
        working-directory: ${{ github.workspace }}/haskell/main
        run: make install

      - name: Run hello
        working-directory: ${{ github.workspace }}/haskell/main
        run: make hello

      - name: Run main test
        working-directory: ${{ github.workspace }}/haskell/main
        run: make runAll

      - name: Cleanup main
        working-directory: ${{ github.workspace }}/haskell/main
        run: make clean

      # Haskell In Depth main (GHC9)
      - name: Install HID
        working-directory: ${{ github.workspace }}/haskell/haskellInDepthGHC9
        run: make install

      - name: Run test HID
        working-directory: ${{ github.workspace }}/haskell/haskellInDepthGHC9
        run: make run

      - name: Cleanup HID
        working-directory: ${{ github.workspace }}/haskell/haskellInDepthGHC9
        run: make clean

      # Haskell In Depth
      - name: Install HID
        working-directory: ${{ github.workspace }}/haskell/haskellInDepth
        run: make install

      - name: Run test HID
        working-directory: ${{ github.workspace }}/haskell/haskellInDepth
        run: make run

      - name: Cleanup HID
        working-directory: ${{ github.workspace }}/haskell/haskellInDepth
        run: make clean


  swift:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        working-directory: ${{ github.workspace }}/swift/test
        run: make compile

      - name: Run
        working-directory: ${{ github.workspace }}/swift/test
        run: make run

      - name: Clean
        working-directory: ${{ github.workspace }}/swift/test
        run: make clean
